"""Nothing keeps README.md's number blocks agreeing with the transcripts that
produce them - until this test.

`scripts/run_part*.py` writes `transcripts/part*-readme-numbers.md` and stops
there; no runner opens `README.md`. The two files agree today only because a
human copied one block into the other by hand at some point. This test closes
that gap without changing how the blocks are produced: it asserts each
generated block still appears, byte for byte, inside README.md, for all four
parts. A regenerated block that was not also pasted into README.md fails
here instead of silently drifting.
"""

import re

import config

OPEN_RE = re.compile(r"<!--\s*Generated by scripts/run_part\d\.py\. Do not edit by hand\. -->")
CLOSE_MARKER = "<!-- End of generated block. -->"


def _generated_blocks(text: str) -> list[str]:
    """Every `<!-- Generated ... -->` ... `<!-- End of generated block. -->`
    span in `text`, each returned as one contiguous string, in file order.

    A block with no close marker (Part 2's, today) runs to the end of the
    file instead - the same fallback a reader scanning by eye would use.
    """
    lines = text.splitlines()
    blocks = []
    i = 0
    while i < len(lines):
        if OPEN_RE.fullmatch(lines[i].strip()):
            start = i
            j = i + 1
            while j < len(lines) and lines[j].strip() != CLOSE_MARKER:
                j += 1
            end = j if j < len(lines) else len(lines) - 1
            blocks.append("\n".join(lines[start : end + 1]))
            i = end + 1
        else:
            i += 1
    return blocks


def test_every_generated_readme_block_appears_verbatim_in_readme():
    readme = (config.REPO_ROOT / "README.md").read_text(encoding="utf-8")

    for part in (1, 2, 3, 4):
        numbers_path = config.TRANSCRIPT_DIR / f"part{part}-readme-numbers.md"
        text = numbers_path.read_text(encoding="utf-8")
        blocks = _generated_blocks(text)
        assert blocks, (
            f"{numbers_path.relative_to(config.REPO_ROOT)} has no "
            f"'Generated by scripts/run_part{part}.py' block to check"
        )
        for block in blocks:
            assert block in readme, (
                f"a block from "
                f"{numbers_path.relative_to(config.REPO_ROOT)} is not present, "
                f"byte for byte, in README.md - regenerate with "
                f"scripts/run_part{part}.py and paste the block in by hand:\n"
                f"{block}"
            )
