"""Build the relational store and write the manifest that guards it.

The manifest hashes the ROWS, not the file. A SQLite file can differ byte for
byte while holding identical data - page layout, freelist state and vacuum
history all leak into the bytes - so hashing the file would produce a test
that fails for reasons nobody can act on.
"""

import hashlib
import json
from datetime import date
from pathlib import Path

import config
import dataset
from db import generate, schema

# Which generator fills which table, in foreign-key-safe insertion order.
_PRIMARY_KEY = {
    "loan_products": "product_code",
    "customers": "customer_id",
    "loan_applications": "record_id",
    "application_events": "event_id",
    "repayments": "repayment_id",
    "support_tickets": "ticket_id",
    "kyc_documents": "document_id",
}


def build_rows() -> dict[str, list[dict]]:
    """Every table's rows, generated in dependency order.

    Each generator opens its own seeded stream, so this ordering affects only
    which rows reference which, never the values any one generator draws.
    """
    products = generate.generate_loan_products()
    customers = generate.generate_customers()
    applications = generate.assign_customers(dataset.RICH_APPLICATIONS, customers)
    return {
        "loan_products": products,
        "customers": customers,
        "loan_applications": applications,
        "application_events": generate.generate_application_events(applications),
        "repayments": generate.generate_repayments(applications),
        "support_tickets": generate.generate_support_tickets(applications, customers),
        "kyc_documents": generate.generate_kyc_documents(customers),
    }


def _columns(table: str) -> list[str]:
    """Column names in declaration order, parsed from the DDL."""
    body = schema.CREATE_STATEMENTS[table].split("(", 1)[1].rsplit(")", 1)[0]
    names = []
    depth = 0
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if depth == 0 and not stripped.upper().startswith(("UNIQUE", "CHECK", "FOREIGN", "PRIMARY KEY (")):
            names.append(stripped.split()[0])
        depth += stripped.count("(") - stripped.count(")")
    return names


def build_database(path=None) -> dict[str, int]:
    """Drop, recreate and fill the database. Returns table name to row count."""
    path = Path(config.DB_PATH if path is None else path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        path.unlink()

    rows = build_rows()
    counts = {}
    conn = schema.connect(path)
    try:
        schema.create_all(conn)
        for table in schema.TABLE_ORDER:
            columns = _columns(table)
            placeholders = ", ".join("?" for _ in columns)
            conn.executemany(
                f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})",
                [tuple(row[c] for c in columns) for row in rows[table]],
            )
            counts[table] = len(rows[table])
        conn.commit()
    finally:
        conn.close()
    return counts


def _canonical_dump(path=None) -> str:
    """Every row, ordered, serialised deterministically. This is what we hash."""
    path = Path(config.DB_PATH if path is None else path)
    conn = schema.connect(path)
    try:
        chunks = []
        for table in schema.TABLE_ORDER:
            key = _PRIMARY_KEY[table]
            columns = _columns(table)
            chunks.append(f"## {table}")
            for row in conn.execute(f"SELECT * FROM {table} ORDER BY {key}"):
                chunks.append(json.dumps([row[c] for c in columns], sort_keys=True))
        return "\n".join(chunks)
    finally:
        conn.close()


def content_hash(path=None) -> str:
    """SHA-256 over the canonical row dump, stable across SQLite file layout."""
    return hashlib.sha256(_canonical_dump(path).encode("utf-8")).hexdigest()


def manifest_text(path=None) -> str:
    """Generate the manifest text for the given path."""
    path = Path(config.DB_PATH if path is None else path)
    conn = schema.connect(path)
    try:
        counts = {
            t: conn.execute(f"SELECT count(*) AS n FROM {t}").fetchone()["n"]
            for t in schema.TABLE_ORDER
        }
    finally:
        conn.close()

    lines = [
        "# Database manifest",
        "",
        f"Generated by `db/build.py` on {date.today().isoformat()}.",
        "Do not edit by hand.",
        "Rebuild with `.venv/bin/python -m db.build`; a test asserts a fresh build still matches this file.",
        "",
        f"The database itself, `{config.DB_PATH.name}`, is gitignored because it is regenerable",
        "and because git cannot diff a binary. This manifest is the committed, readable record of it.",
        "",
        "## Reproducibility",
        "",
        f"- Seed: `{config.SEED}`",
        "- One seeded sub-stream per table, so adding a table disturbs no existing row:",
        "",
        "| Table | Stream offset | Effective seed |",
        "|---|---|---|",
    ]
    for table, offset in sorted(config.STREAM_OFFSETS.items(), key=lambda kv: kv[1]):
        lines.append(f"| `{table}` | {offset} | {config.SEED + offset} |")
    lines += [
        "",
        "`loan_applications` keeps offset 0, which is the original `Random(SEED)`.",
        "That is why every value of the brief's six fields in `data/loan_applications.json`",
        "is unchanged by the store (D-18) and by the time axis (D-26), which added two fields",
        "without moving one existing cell.",
        "",
        "## Row counts",
        "",
        "| Table | Rows |",
        "|---|---|",
    ]
    for table in schema.TABLE_ORDER:
        lines.append(f"| `{table}` | {counts[table]} |")
    lines += [
        f"| **total** | **{sum(counts.values())}** |",
        "",
        "## Content hash",
        "",
        "SHA-256 over a canonically ordered dump of every row, not over the file bytes,",
        "because a SQLite file can differ byte for byte while holding identical data.",
        "",
        "```",
        content_hash(path),
        "```",
        "",
        "## Schema",
        "",
    ]
    for table in schema.TABLE_ORDER:
        lines += ["```sql", schema.CREATE_STATEMENTS[table].strip(), "```", ""]
    return "\n".join(lines)


def write_manifest(path=None) -> Path:
    """Write the manifest to the target path."""
    target = Path(config.DB_MANIFEST)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(manifest_text(path), encoding="utf-8")
    return target


def main() -> None:
    """Build the database and write the manifest."""
    counts = build_database()
    print(f"built {config.DB_PATH}")
    for table, n in counts.items():
        print(f"  {table:<22} {n:>6} rows")
    print(f"  {'total':<22} {sum(counts.values()):>6} rows")
    manifest = write_manifest()
    print(f"wrote {manifest}")
    print(f"content hash {content_hash()}")


if __name__ == "__main__":
    main()
