"""Run every Part 4 task in order and write the graded transcripts.

Nothing in README.md's Part 4 number block is typed by hand. This script
writes transcripts/part4-readme-numbers.md and README.md carries that block,
same rule as scripts/run_part1.py and scripts/run_part2.py, and the same
reason.
"""

import asyncio
import os
import re
import shlex
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
os.environ.setdefault("ANONYMIZED_TELEMETRY", "False")

import config  # noqa: E402
from agent import checkpoint, graph, memory, nodes, tools  # noqa: E402
from agent.state import new_state  # noqa: E402
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver  # noqa: E402
from langgraph.errors import NodeTimeoutError  # noqa: E402

HEADER = (
    "Generated by scripts/run_part4.py under MOCK_LLM with zero API keys and\n"
    "zero outbound network access. Reproduce with: "
    ".venv/bin/python scripts/run_part4.py\n"
)


def write(name: str, body: str) -> Path:
    config.TRANSCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    path = config.TRANSCRIPT_DIR / name
    path.write_text(f"{HEADER}\n{body}", encoding="utf-8")
    print(f"  wrote {path.relative_to(config.REPO_ROOT)}")
    return path


def _forget(thread_id: str) -> None:
    """Delete one thread's persisted conversation, so a demo starts fresh.

    Without this, running the script twice resumes turn counts and prior
    answers from data/conversations/, the same problem
    scripts/run_part2.py::fresh_ask exists to avoid, and for the same reason:
    same input has to mean same bytes.
    """
    path = memory.path_for(thread_id)
    if path.exists():
        path.unlink()


# --- Task 14, the MCP round trip -------------------------------------------


def _poll_ready(url: str, proc: subprocess.Popen, attempts: int = 100, interval: float = 0.05) -> None:
    """Poll until the server answers, or fail loudly with its stderr.

    Any HTTP response, even an error status, proves the socket is listening
    and the ASGI app is serving - that is all readiness needs to mean here,
    and it is checked directly rather than assumed after a fixed sleep. A
    bare `sleep` is either flaky on a loaded machine or slow on a fast one.
    """
    for _ in range(attempts):
        if proc.poll() is not None:
            break
        try:
            urllib.request.urlopen(url, timeout=1)
            return
        except urllib.error.HTTPError:
            return  # the server answered, even if with an HTTP error status
        except urllib.error.URLError:
            time.sleep(interval)
    stderr = proc.stderr.read().decode("utf-8", errors="replace") if proc.stderr else ""
    raise RuntimeError(
        f"mcp_server.server never answered at {url} after {attempts} attempts "
        f"({attempts * interval:.1f}s budget).\n"
        f"--- server stderr ---\n{stderr}"
    )


def _python_invocation(*args: str) -> str:
    """The command a subprocess call actually used, safe for a transcript.

    sys.executable is an absolute path, and in a git worktree .venv is often
    a symlink resolving outside the worktree entirely (it is here), so
    printing it verbatim would put a machine- and checkout-specific path
    into a committed, byte-guarded file. Rendered relative to
    config.REPO_ROOT when that succeeds; otherwise normalised to
    ".venv/bin/python", the invocation every command in CLAUDE.md and this
    repository's own scripts already assume. Built from the same argv the
    subprocess call receives, so the printed line and the real command
    cannot drift apart.
    """
    executable = Path(sys.executable).resolve()
    try:
        python = str(executable.relative_to(config.REPO_ROOT))
    except ValueError:
        python = ".venv/bin/python"
    return shlex.join([python, *args])


def mcp_transcript() -> str:
    """Task 14. A real client-server round trip over loopback HTTP.

    The server is the only thing in the repository that binds a port, and
    the port is released on every exit path via `finally`, including a
    readiness failure or a client crash. Loopback HTTP only - nothing leaves
    the machine, so this does not touch the offline ground rule.
    """
    server_argv = ["-m", "mcp_server.server"]
    client_argv = ["mcp_client.py", "--url", config.MCP_URL, "LN-1042", "LN-1057"]
    lines = [
        "PART 4 TASK 14 - MCP, A REAL CLIENT-SERVER ROUND TRIP",
        "",
        f"subprocess 1 (server): {_python_invocation(*server_argv)}",
        f"subprocess 2 (client): {_python_invocation(*client_argv)}",
        f"url: {config.MCP_URL}",
        "",
        "These are two separate OS processes talking over loopback HTTP; the",
        "client never imports or starts the server (see mcp_client.py).",
        "",
    ]
    proc = subprocess.Popen(
        [sys.executable, *server_argv],
        cwd=config.REPO_ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        _poll_ready(config.MCP_URL, proc)
        lines.append(f"server ready at {config.MCP_URL}")
        lines.append("")
        client = subprocess.run(
            [sys.executable, *client_argv],
            cwd=config.REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        lines.append("client (mcp_client.py) stdout, verbatim:")
        lines.append("")
        lines.append(client.stdout.rstrip("\n"))
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=5)
    return "\n".join(lines) + "\n"


# --- Tasks 15 and 16, resilience --------------------------------------------


def _drop_elapsed(message: str) -> str:
    """Strip the "(elapsed: ...s)" parenthetical from a NodeTimeoutError's
    message.

    That figure is a wall-clock reading with no deterministic value on any
    machine, at any decimal precision - rounding only narrows the window in
    which two runs can disagree, it does not close it. D-70 already states
    the principle for exactly this: a clock reading is a side channel that
    never reaches a committed, byte-guarded artefact, and a transcript is
    such an artefact. The claim this demonstration makes is that the node
    raised NodeTimeoutError rather than hanging; that claim needs the
    exception type and the budget it breached, not the observed duration, so
    the duration is removed rather than rounded.
    """
    return re.sub(r"\s*\(elapsed: [\d.]+s\)", "", message)


def _retry_demo() -> list[str]:
    """Demonstration 1. A transient failure, recovered by the retry policy."""
    trace: list[str] = []
    calls = {"n": 0}
    real = tools.check_loan_application_status

    def flaky(record_id: str):
        calls["n"] += 1
        n = calls["n"]
        if n <= 2:
            trace.append(f"  attempt {n}: raised ConnectionError('simulated transient failure {n}')")
            raise ConnectionError(f"simulated transient failure {n}")
        result = real(record_id)
        trace.append(f"  attempt {n}: succeeded, found={result['found']}")
        return result

    _forget("part4-retry")
    tools.check_loan_application_status = flaky
    graph.compiled.cache_clear()
    try:
        response = graph.ask("What is the status of LN-1042?", thread_id="part4-retry")
    finally:
        tools.check_loan_application_status = real
        graph.compiled.cache_clear()

    return [
        "DEMONSTRATION 1 - THE RETRY POLICY RECOVERS A TRANSIENT FAILURE",
        "",
        "shim: agent.tools.check_loan_application_status raises ConnectionError",
        "on its first two calls, then answers for real on the third. It lives",
        "here, not in the graph (D-76).",
        "",
        f"retry policy (agent/graph.py::RETRY_POLICY, attached to "
        f"{graph.RESILIENT_NODE!r}):",
        f"  max attempts    = {config.RETRY_MAX_ATTEMPTS}",
        f"  initial interval= {config.RETRY_INITIAL_INTERVAL}s",
        f"  max interval    = {config.RETRY_MAX_INTERVAL}s",
        f"  backoff factor  = {config.RETRY_BACKOFF_FACTOR}",
        f"  jitter          = {config.RETRY_JITTER}",
        "",
        *trace,
        "",
        f"attempts spent: {calls['n']} of {config.RETRY_MAX_ATTEMPTS} allowed",
        f"route: {response['route']}   found: {response['lookup']['found']}",
    ]


def _node_timeout_demo() -> list[str]:
    """Demonstration 2. One node over its own budget raises, not hangs."""
    real = tools.check_loan_application_status
    original_node_timeout = config.NODE_TIMEOUT_SECONDS
    demo_timeout = 0.1

    def slow(record_id: str):
        time.sleep(demo_timeout + 0.2)
        raise AssertionError("the timeout should have fired before this line")

    _forget("part4-node-timeout")
    tools.check_loan_application_status = slow
    config.NODE_TIMEOUT_SECONDS = demo_timeout
    graph.compiled.cache_clear()
    caught = None
    try:
        graph.ask("What is the status of LN-1042?", thread_id="part4-node-timeout")
    except NodeTimeoutError as exc:
        caught = exc
    finally:
        tools.check_loan_application_status = real
        config.NODE_TIMEOUT_SECONDS = original_node_timeout
        graph.compiled.cache_clear()

    if caught is None:
        raise RuntimeError(
            "expected NodeTimeoutError from the per-node budget; it did not fire"
        )

    return [
        "DEMONSTRATION 2 - A NODE OVER ITS OWN BUDGET RAISES CLEANLY",
        "",
        f"shim: agent.tools.check_loan_application_status sleeps past a "
        f"{demo_timeout}s per-node budget (config.NODE_TIMEOUT_SECONDS is "
        f"{original_node_timeout}s normally, narrowed here so the demo does "
        f"not wait on a real timeout) instead of doing the record read it "
        f"pretends to do.",
        "",
        f"exception type: {type(caught).__name__}",
        f"configured per-node budget for this demonstration: {demo_timeout}s "
        f"(config.NODE_TIMEOUT_SECONDS is {original_node_timeout}s normally)",
        f"message: {_drop_elapsed(str(caught))}",
    ]


def _global_timeout_demo() -> list[str]:
    """Demonstration 3. A run over the whole-run budget is cancelled outright."""
    real = tools.check_loan_application_status
    original_graph_timeout = config.GRAPH_TIMEOUT_SECONDS
    demo_timeout = 0.2

    def slow(record_id: str):
        time.sleep(1)
        raise AssertionError("the global timeout should have fired first")

    _forget("part4-global-timeout")
    tools.check_loan_application_status = slow
    config.GRAPH_TIMEOUT_SECONDS = demo_timeout
    graph.compiled.cache_clear()

    async def run() -> bool:
        try:
            await graph.ask_async(
                "What is the status of LN-1042?", thread_id="part4-global-timeout"
            )
        except (asyncio.TimeoutError, TimeoutError):
            return True
        return False

    try:
        cancelled = asyncio.run(run())
    finally:
        tools.check_loan_application_status = real
        config.GRAPH_TIMEOUT_SECONDS = original_graph_timeout
        graph.compiled.cache_clear()

    if not cancelled:
        raise RuntimeError(
            "expected the global budget to cancel ainvoke; it did not fire"
        )

    return [
        "DEMONSTRATION 3 - A RUN OVER THE GLOBAL BUDGET IS CANCELLED",
        "",
        f"shim: agent.tools.check_loan_application_status sleeps 1s, well "
        f"inside its own per-node budget ({config.NODE_TIMEOUT_SECONDS}s) so "
        f"only the whole-run budget can be the one that fires. "
        f"config.GRAPH_TIMEOUT_SECONDS is narrowed to {demo_timeout}s for "
        f"this demonstration only (normally {original_graph_timeout}s).",
        "",
        "asyncio.wait_for around ainvoke (agent/graph.py::ask_async) raised",
        "TimeoutError before the node's sleep(1) returned: the whole run was",
        "cancelled by the global budget, not by the per-node one.",
    ]


def resilience_transcript() -> str:
    """Tasks 15 and 16. The three demonstrations, back to back."""
    lines = ["PART 4 TASKS 15 AND 16 - RESILIENCE", ""]
    lines += _retry_demo()
    lines.append("")
    lines += _node_timeout_demo()
    lines.append("")
    lines += _global_timeout_demo()
    return "\n".join(lines) + "\n"


# --- Task 15, checkpointed resume -------------------------------------------


def checkpoint_transcript() -> str:
    """Task 15. The two invocations, and which nodes each one ran.

    Persisted under config.CHECKPOINT_PATH via agent.checkpoint.conn_string()
    rather than ":memory:", so checkpoints.sqlite exists on disk afterwards
    and this transcript can say so, and that it holds the thread.
    """
    thread_id = "part4-checkpoint-demo"
    query = "What is the status of LN-1042?"
    _forget(thread_id)

    entered: list[str] = []
    originals = {name: getattr(nodes, name) for name in nodes.NODE_NAMES}

    def _wrap(fn, label):
        if asyncio.iscoroutinefunction(fn):
            async def recorded(state):
                entered.append(label)
                return await fn(state)
        else:
            def recorded(state):
                entered.append(label)
                return fn(state)
        return recorded

    for name, fn in originals.items():
        setattr(nodes, name, _wrap(fn, name))

    async def run():
        async with AsyncSqliteSaver.from_conn_string(checkpoint.conn_string()) as saver:
            compiled = checkpoint.checkpointed(saver)
            thread_config = {"configurable": {"thread_id": thread_id}}
            await compiled.ainvoke(new_state(query, thread_id, 1), thread_config)
            run_one = list(entered)
            entered.clear()
            final = await compiled.ainvoke(None, thread_config)
            run_two = list(entered)
            return run_one, run_two, final

    try:
        run_one, run_two, final = asyncio.run(run())
    finally:
        for name, fn in originals.items():
            setattr(nodes, name, fn)

    resumed_twice = sorted(set(run_one) & set(run_two))

    lines = [
        "PART 4 TASK 15 - CHECKPOINTED RESUME",
        "",
        f"query: {query}",
        f"thread_id: {thread_id!r}",
        f"interrupt_before: {checkpoint.INTERRUPT_BEFORE!r}",
        f"checkpoint file: {config.CHECKPOINT_PATH.relative_to(config.REPO_ROOT)}",
        "",
        "RUN 1 (fresh thread, stops right before the interrupt)",
        f"  nodes entered: {', '.join(run_one)}",
        "",
        "RUN 2 (same thread_id, resumed by invoking with input=None)",
        f"  nodes entered: {', '.join(run_two)}",
        "",
        f"nodes loaded from the checkpoint rather than re-executed in run 2: "
        f"{', '.join(sorted(run_one))}",
        f"nodes that ran in both invocations (should be none): "
        f"{', '.join(resumed_twice) if resumed_twice else 'none'}",
        "",
        f"checkpoints.sqlite exists on disk: {config.CHECKPOINT_PATH.exists()}",
        f"final answer present after resume: {bool(final['response']['answer'])}",
    ]
    return "\n".join(lines) + "\n"


# --- The README number block -------------------------------------------------


def readme_numbers() -> str:
    """The block README.md carries. Never typed by hand."""
    return "\n".join(
        [
            "<!-- Generated by scripts/run_part4.py. Do not edit by hand. -->",
            "",
            "| Part 4 measurement | Value |",
            "|---|---|",
            f"| Graph nodes | {len(graph.node_names())} |",
            f"| Retry max attempts | {config.RETRY_MAX_ATTEMPTS} |",
            f"| Retry initial interval | {config.RETRY_INITIAL_INTERVAL}s |",
            f"| Retry max interval | {config.RETRY_MAX_INTERVAL}s |",
            f"| Retry backoff factor | {config.RETRY_BACKOFF_FACTOR} |",
            f"| Retry jitter | {config.RETRY_JITTER} |",
            f"| Per-node timeout budget | {config.NODE_TIMEOUT_SECONDS}s |",
            f"| Whole-run timeout budget | {config.GRAPH_TIMEOUT_SECONDS}s |",
            f"| MCP URL | {config.MCP_URL} |",
            "",
            "<!-- End of generated block. -->",
            "",
        ]
    )


def require_mock_provider() -> None:
    """Refuse to write graded artefacts under a real provider (D-68).

    transcripts/ and the README number blocks are byte-guarded, and a real
    model is not bit-reproducible. Without this, one forgotten line in .env
    rewrites them and the diff looks like a legitimate retune.
    """
    provider = config.resolve_provider()
    if provider != config.DEFAULT_PROVIDER:
        sys.exit(
            f"Refusing to run: LLM_PROVIDER={provider!r}. This script writes "
            f"graded, byte-guarded artefacts and only {config.DEFAULT_PROVIDER!r} "
            f"is reproducible. Unset LLM_PROVIDER, or use "
            f"scripts/run_groq_demo.py to exercise the real provider."
        )


def require_database() -> None:
    """Refuse before writing anything if the gitignored database is missing.

    Every demonstration here looks up LN-1042 through agent.tools, which
    reads config.DB_PATH. A clean clone is exactly the case a grader runs,
    and data/ is gitignored.
    """
    import sqlite3

    if config.DB_PATH.exists():
        conn = sqlite3.connect(str(config.DB_PATH))
        try:
            found = conn.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='table' AND name='loan_applications'"
            ).fetchone()
        finally:
            conn.close()
        if found:
            return

    raise SystemExit(
        f"{config.DB_PATH.relative_to(config.REPO_ROOT)} is missing or empty, and "
        "every lookup demonstration here reads it.\n"
        "It is gitignored and regenerable in about a second:\n"
        "  .venv/bin/python -m db.build"
    )


def require_no_stray_uploads() -> None:
    """Refuse to write graded artefacts while data/uploads/ holds a file.

    rag/retrieve.py's product narrowing reads config.UPLOAD_DIR live and
    unions its doc ids into every product-named query (D-72's V2 note). A
    file left there by a manual /add-document session, a crashed test, or an
    interrupted run would silently join that union here too and move
    transcripts/ and the README number blocks, with no code change and no
    error - the same failure shape require_mock_provider guards against for a
    real provider.

    Every demonstration this script runs is lookup-routed, so it does not
    reach rag/retrieve.py today - but that is what makes this a guard against
    a future demonstration silently breaking, not evidence the guard is
    unnecessary, and the other two runners carry it in exactly this spot.
    """
    if config.UPLOAD_DIR.exists():
        stray = sorted(p.name for p in config.UPLOAD_DIR.iterdir())
        if stray:
            sys.exit(
                f"Refusing to run: {config.UPLOAD_DIR.relative_to(config.REPO_ROOT)} "
                f"holds {stray}. rag/retrieve.py's product narrowing reads this "
                f"directory live, so a stray upload would move graded, "
                f"byte-guarded artefacts with no code change. Clear it first: "
                f"rm -r {config.UPLOAD_DIR.relative_to(config.REPO_ROOT)}"
            )


def main() -> None:
    print("Part 4. Writing transcripts under MOCK_LLM.")
    require_mock_provider()  # before require_database, and both before any write
    require_no_stray_uploads()  # same reasoning, same place
    require_database()  # before the first write, never after

    if config.CHECKPOINT_PATH.exists():
        # Run 1 of the checkpoint demonstration has to be a genuinely fresh
        # thread. Without this, the second run of this script resumes a
        # thread that already reached END, and the transcript changes - the
        # same failure mode scripts/run_part2.py::fresh_ask exists to avoid.
        config.CHECKPOINT_PATH.unlink()

    write("part4-mcp.txt", mcp_transcript())
    write("part4-resilience.txt", resilience_transcript())
    write("part4-checkpoint.txt", checkpoint_transcript())

    numbers_path = config.TRANSCRIPT_DIR / "part4-readme-numbers.md"
    numbers_path.write_text(readme_numbers(), encoding="utf-8")
    print(f"  wrote {numbers_path.relative_to(config.REPO_ROOT)}")
    print("Done.")


if __name__ == "__main__":
    main()
