"""Run every Part 1 task in order and write the graded transcripts.

Nothing in README.md's number tables is typed by hand. This script writes
transcripts/part1-readme-numbers.md, and README.md carries that block, so a
retune that moves a number moves it in both places or in neither.
"""

import io
import os
import statistics
import sys
from contextlib import redirect_stdout
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
os.environ.setdefault("ANONYMIZED_TELEMETRY", "False")

import config  # noqa: E402
import dataset  # noqa: E402
from eval import calibration  # noqa: E402
from eval.queries import EVAL_QUERIES  # noqa: E402
from rag import chunking, evaluate, generate, index, kb  # noqa: E402

HEADER = (
    "Generated by scripts/run_part1.py under MOCK_LLM with zero API keys and\n"
    "zero network access. Reproduce with: .venv/bin/python scripts/run_part1.py\n"
)


def write(name: str, body: str) -> Path:
    """Write the transcript to the target path."""
    config.TRANSCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    path = config.TRANSCRIPT_DIR / name
    path.write_text(f"{HEADER}\n{body}", encoding="utf-8")
    print(f"  wrote {path.relative_to(config.REPO_ROOT)}")
    return path


def dataset_transcript() -> str:
    """Generate the dataset transcript."""
    buffer = io.StringIO()
    with redirect_stdout(buffer):
        dataset.main()
    return buffer.getvalue()


def knowledge_base_transcript() -> str:
    """Describe the knowledge base: what is in it, how long it is, how it embeds.

    Task 2 produces no computed result the way the other tasks do - the
    documents are the deliverable. So this measures them instead, and the one
    measurement that can actually fail is the last section: a chunk longer than
    the embedder's sequence limit is truncated silently, which would corrupt
    every similarity in Tasks 4 and 5 with nothing reporting it.
    """
    documents = kb.load_documents()
    tokenizer = index.get_embedder().tokenizer
    limit = index.get_embedder().max_seq_length

    rows = []
    for document in documents:
        rows.append(
            {
                "doc": document,
                "sentences": len(chunking.chunk_sentences(document.body)),
                "words": len(document.body.split()),
                "chars": len(document.body),
                "tokens": len(tokenizer.encode(document.body)),
            }
        )

    required = [r for r in rows if r["doc"].required]
    neighbours = [r for r in rows if not r["doc"].required]

    def spread(key):
        values = sorted(r[key] for r in rows)
        return values[0], statistics.median(values), values[-1]

    lines = [
        "Task 2 - the knowledge base",
        "",
        f"{len(documents)} documents in knowledge_base/, one plain-text file each, every one",
        f"written for this brief. {len(required)} cover a topic the brief names; "
        f"{len(neighbours)} are deliberately",
        "confusable neighbours, there so that a query has more than one plausible",
        "parent and Precision@3 has room to move (D-04).",
        "",
        "The documents carry no metadata of their own: a file is the prose a support",
        f"team would write, and what it is about lives beside it in {kb.CATALOGUE_NAME}",
        "(D-32). rag/kb.py parses both strictly and refuses to load if they disagree,",
        "in either direction, because a body with no entry would embed with no topic and",
        "an entry with no body would leave a doc_id retrieval can never return.",
        "",
        f"{'doc_id':<38} {'role':<10} {'sent':>5} {'words':>6} {'chars':>6} {'tokens':>7}",
        f"{'-' * 38} {'-' * 10} {'-' * 5} {'-' * 6} {'-' * 6} {'-' * 7}",
    ]
    for row in rows:
        lines.append(
            f"{row['doc'].doc_id:<38} "
            f"{'required' if row['doc'].required else 'neighbour':<10} "
            f"{row['sentences']:>5} {row['words']:>6} {row['chars']:>6} {row['tokens']:>7}"
        )
    lines += [
        f"{'-' * 38} {'-' * 10} {'-' * 5} {'-' * 6} {'-' * 6} {'-' * 7}",
        f"{'totals':<38} {'':<10} "
        f"{sum(r['sentences'] for r in rows):>5} "
        f"{sum(r['words'] for r in rows):>6} "
        f"{sum(r['chars'] for r in rows):>6} "
        f"{sum(r['tokens'] for r in rows):>7}",
        "",
        f"{'spread per document':<24} {'min':>6} {'median':>8} {'max':>6}",
    ]
    for label, key in (("sentences", "sentences"), ("words", "words"), ("tokens", "tokens")):
        low, mid, high = spread(key)
        lines.append(f"{label:<24} {low:>6} {mid:>8.0f} {high:>6}")

    brief_max = 5
    over_brief = sum(1 for r in rows if r["sentences"] > brief_max)
    over_limit = sum(1 for r in rows if r["tokens"] > limit)

    lines += [
        "",
        "Length, against the brief",
        "",
        f"  The brief asks for 2 to 5 sentences per document. All {over_brief} of these are",
        "  longer, by design: D-05 chose 10 to 15 sentences targeting 12, because at 2 to 5",
        "  both chunking strategies produce nearly the same chunks and Task 5's comparison",
        "  degenerates to a tie. This is a stated override, not an accident.",
        "",
        "Length, against the embedder",
        "",
        f"  {config.EMBEDDING_MODEL} truncates at {limit} tokens per sequence.",
        f"  {over_limit} of {len(rows)} documents are longer than that whole.",
        "",
        "  That is harmless only because no document is ever embedded whole: chunking runs",
        "  first, and every chunk is embedded on its own. The check that matters is whether",
        "  any chunk exceeds the limit, because a chunk that does is truncated silently and",
        "  every similarity measured downstream would be wrong with nothing reporting it.",
        "",
        f"  {'strategy':<12} {'chunks':>7} {'longest chunk':>15} {'limit':>7} {'verdict':>10}",
    ]
    for strategy in sorted(config.COLLECTION_FOR_STRATEGY):
        texts = [c.text for c in index.build_chunks(strategy, documents)]
        longest = max(len(tokenizer.encode(t)) for t in texts)
        lines.append(
            f"  {strategy:<12} {len(texts):>7} {longest:>15} {limit:>7} "
            f"{'ok' if longest <= limit else 'TRUNCATED':>10}"
        )

    lines += [
        "",
        "The required topics",
        "",
    ]
    for row in required:
        lines.append(f"  {row['doc'].doc_id:<38} {row['doc'].title}")
    lines += [
        "",
        "The confusable neighbours",
        "",
    ]
    for row in neighbours:
        lines.append(f"  {row['doc'].doc_id:<38} {row['doc'].title}")
    lines += [
        "",
        "  Which required topic each one sits next to, and why it is confusable, is",
        "  recorded once in docs/superpowers/specs/2026-09-10-loan-support-agent-design.md section 6.2",
        "  rather than restated here.",
    ]
    return "\n".join(lines) + "\n"


def indexing_summary() -> tuple[str, dict]:
    """Generate the indexing summary."""
    counts = index.build_index(rebuild=True)
    documents = kb.load_documents()
    lines = [
        "Task 3 - chunking and indexing",
        "",
        f"documents: {len(documents)} "
        f"({sum(1 for d in documents if d.required)} required topics, "
        f"{sum(1 for d in documents if not d.required)} confusable neighbours)",
        f"fixed-size parameters: size {config.CHUNK_SIZE}, overlap {config.CHUNK_OVERLAP}",
        f"embedding model: {config.EMBEDDING_MODEL}, normalised, cosine space",
        "",
        f"{'document':<40} {'fixed':>6} {'sentences':>10}",
    ]
    per_strategy = {
        s: index.chunk_counts_by_document(s) for s in sorted(config.COLLECTION_FOR_STRATEGY)
    }
    for document in documents:
        lines.append(
            f"{document.doc_id:<40} "
            f"{per_strategy[config.STRATEGY_FIXED][document.doc_id]:>6} "
            f"{per_strategy[config.STRATEGY_SENTENCES][document.doc_id]:>10}"
        )
    lines += ["", "collection totals"]
    for name, total in sorted(counts.items()):
        lines.append(f"  {name:<22} {total:>5} chunks")
    return "\n".join(lines) + "\n", counts


def _one_answer(result, label: str) -> list[str]:
    """Generate one answer."""
    lines = [
        f"[{label}] {result.query}",
        f"  top-1 similarity : {result.top1_similarity:.4f}  "
        f"(threshold {config.SIMILARITY_THRESHOLD})",
        f"  retrieved parents: {[h.doc_id for h in result.hits]}",
        f"  supported        : {result.supported}",
        f"  citations        : {list(result.citations)}",
        "  answer           :",
    ]
    for line in result.text.splitlines():
        lines.append(f"    {line}")
    lines.append("")
    return lines


def generation_transcript() -> str:
    """Generate the generation transcript."""
    lines = [
        "Task 4 - grounded generation and the I-do-not-know fallback",
        "",
        f"threshold T = {config.SIMILARITY_THRESHOLD} (measured, see part1-calibration.txt)",
        f"support rule: at least {config.SUPPORT_MIN_SHARED} of the top "
        f"{config.TOP_K} chunks share one parent document",
        "",
    ]
    for strategy in sorted(config.COLLECTION_FOR_STRATEGY):
        lines += [
            f"=== collection: {config.COLLECTION_FOR_STRATEGY[strategy]} ===",
            "",
            "--- in-scope queries ---",
            "",
        ]
        for query in EVAL_QUERIES:
            lines += _one_answer(generate.answer(query.text, strategy), query.query_id)
        lines += ["--- deliberately out-of-scope queries ---", ""]
        for probe in calibration.OUT_OF_SCOPE_PROBES[:2]:
            lines += _one_answer(generate.answer(probe, strategy), "OOS")
    return "\n".join(lines)


def readme_numbers(summary: dict, counts: dict) -> str:
    """Generate the README numbers."""
    scores = {s: evaluate.evaluate(s) for s in sorted(config.COLLECTION_FOR_STRATEGY)}
    mean_r = {
        s: sum(len(q.retrieved) for q in scores[s][0]) / len(scores[s][0]) for s in scores
    }
    report = dataset.validation_report()

    lines = [
        f"<!-- Generated by scripts/run_part1.py on {date.today().isoformat()}. Do not edit by hand. -->",
        "",
        "### Dataset",
        "",
        "| Seed | Records | Fraud flagged | Categories | Statuses |",
        "|---|---|---|---|---|",
        f"| `{report['seed']}` | {report['total']} | "
        f"{report['fraud_flagged']} ({report['fraud_percentage']}%) | "
        f"{len(report['by_category'])} | {len(report['by_status'])} |",
        "",
        "### Threshold calibration",
        "",
        "| Measurement | Value |",
        "|---|---|",
        f"| Minimum in-scope top-1 similarity | {summary['min_in_scope']:.4f} |",
        f"| Maximum out-of-scope top-1 similarity | {summary['max_out_of_scope']:.4f} |",
        f"| Gap between the clusters | {summary['gap']:.4f} |",
        f"| **Chosen threshold T** | **{summary['threshold']:.4f}** |",
        "",
        "### Chunking comparison",
        "",
        "| Collection | Chunks | Mean \\|R\\| | Precision@3 | Recall@3 |",
        "|---|---|---|---|---|",
    ]
    for strategy in sorted(scores):
        name = config.COLLECTION_FOR_STRATEGY[strategy]
        _, precision, recall = scores[strategy]
        lines.append(
            f"| `{name}` | {counts[name]} | {mean_r[strategy]:.2f} | "
            f"{precision:.4f} | {recall:.4f} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    """Main function."""
    print("Part 1 - running every task under MOCK_LLM")
    print()

    print("Task 1: dataset")
    write("part1-dataset.txt", dataset_transcript())

    print("Task 2: knowledge base")
    write("part1-knowledge-base.txt", knowledge_base_transcript())

    print("Task 3: chunking and indexing")
    index_body, counts = indexing_summary()

    print("Task 4: threshold calibration")
    summary = calibration.calibrate()
    write("part1-calibration.txt", index_body + "\n" + calibration.format_report(summary))

    print("Task 4: grounded generation")
    write("part1-generation.txt", generation_transcript())

    print("Task 5: chunking comparison")
    write("part1-evaluation.txt", evaluate.format_comparison())

    print("README number tables")
    write("part1-readme-numbers.md", readme_numbers(summary, counts))

    print()
    print(f"threshold in config.py: {config.SIMILARITY_THRESHOLD}")
    print(f"threshold measured now: {summary['threshold']}")
    if config.SIMILARITY_THRESHOLD != summary["threshold"]:
        print(
            "  NOTE: the measured midpoint has moved. Update config.SIMILARITY_THRESHOLD "
            "and README.md together, then re-run."
        )


if __name__ == "__main__":
    main()
