"""Run every Part 1 task in order and write the graded transcripts.

Nothing in README.md's number tables is typed by hand. This script writes
transcripts/part1-readme-numbers.md, and README.md carries that block, so a
retune that moves a number moves it in both places or in neither.
"""

import io
import os
import sys
from contextlib import redirect_stdout
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
os.environ.setdefault("ANONYMIZED_TELEMETRY", "False")

import config  # noqa: E402
import dataset  # noqa: E402
from eval import calibration  # noqa: E402
from eval.queries import EVAL_QUERIES  # noqa: E402
from rag import evaluate, generate, index, kb  # noqa: E402

HEADER = (
    "Generated by scripts/run_part1.py under MOCK_LLM with zero API keys and\n"
    "zero network access. Reproduce with: .venv/bin/python scripts/run_part1.py\n"
)


def write(name: str, body: str) -> Path:
    config.TRANSCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    path = config.TRANSCRIPT_DIR / name
    path.write_text(f"{HEADER}\n{body}", encoding="utf-8")
    print(f"  wrote {path.relative_to(config.REPO_ROOT)}")
    return path


def dataset_transcript() -> str:
    buffer = io.StringIO()
    with redirect_stdout(buffer):
        dataset.main()
    return buffer.getvalue()


def indexing_summary() -> tuple[str, dict]:
    counts = index.build_index(rebuild=True)
    documents = kb.load_documents()
    lines = [
        "Task 3 - chunking and indexing",
        "",
        f"documents: {len(documents)} "
        f"({sum(1 for d in documents if d.required)} required topics, "
        f"{sum(1 for d in documents if not d.required)} confusable neighbours)",
        f"fixed-size parameters: size {config.CHUNK_SIZE}, overlap {config.CHUNK_OVERLAP}",
        f"embedding model: {config.EMBEDDING_MODEL}, normalised, cosine space",
        "",
        f"{'document':<40} {'fixed':>6} {'sentences':>10}",
    ]
    per_strategy = {
        s: index.chunk_counts_by_document(s) for s in sorted(config.COLLECTION_FOR_STRATEGY)
    }
    for document in documents:
        lines.append(
            f"{document.doc_id:<40} "
            f"{per_strategy[config.STRATEGY_FIXED][document.doc_id]:>6} "
            f"{per_strategy[config.STRATEGY_SENTENCES][document.doc_id]:>10}"
        )
    lines += ["", "collection totals"]
    for name, total in sorted(counts.items()):
        lines.append(f"  {name:<22} {total:>5} chunks")
    return "\n".join(lines) + "\n", counts


def _one_answer(result, label: str) -> list[str]:
    lines = [
        f"[{label}] {result.query}",
        f"  top-1 similarity : {result.top1_similarity:.4f}  "
        f"(threshold {config.SIMILARITY_THRESHOLD})",
        f"  retrieved parents: {[h.doc_id for h in result.hits]}",
        f"  supported        : {result.supported}",
        f"  citations        : {list(result.citations)}",
        "  answer           :",
    ]
    for line in result.text.splitlines():
        lines.append(f"    {line}")
    lines.append("")
    return lines


def generation_transcript() -> str:
    lines = [
        "Task 4 - grounded generation and the I-do-not-know fallback",
        "",
        f"threshold T = {config.SIMILARITY_THRESHOLD} (measured, see part1-calibration.txt)",
        f"support rule: at least {config.SUPPORT_MIN_SHARED} of the top "
        f"{config.TOP_K} chunks share one parent document",
        "",
    ]
    for strategy in sorted(config.COLLECTION_FOR_STRATEGY):
        lines += [
            f"=== collection: {config.COLLECTION_FOR_STRATEGY[strategy]} ===",
            "",
            "--- in-scope queries ---",
            "",
        ]
        for query in EVAL_QUERIES:
            lines += _one_answer(generate.answer(query.text, strategy), query.query_id)
        lines += ["--- deliberately out-of-scope queries ---", ""]
        for probe in calibration.OUT_OF_SCOPE_PROBES[:2]:
            lines += _one_answer(generate.answer(probe, strategy), "OOS")
    return "\n".join(lines)


def readme_numbers(summary: dict, counts: dict) -> str:
    scores = {s: evaluate.evaluate(s) for s in sorted(config.COLLECTION_FOR_STRATEGY)}
    mean_r = {
        s: sum(len(q.retrieved) for q in scores[s][0]) / len(scores[s][0]) for s in scores
    }
    report = dataset.validation_report()

    lines = [
        f"<!-- Generated by scripts/run_part1.py on {date.today().isoformat()}. Do not edit by hand. -->",
        "",
        "### Dataset",
        "",
        "| Seed | Records | Fraud flagged | Categories | Statuses |",
        "|---|---|---|---|---|",
        f"| `{report['seed']}` | {report['total']} | "
        f"{report['fraud_flagged']} ({report['fraud_percentage']}%) | "
        f"{len(report['by_category'])} | {len(report['by_status'])} |",
        "",
        "### Threshold calibration",
        "",
        "| Measurement | Value |",
        "|---|---|",
        f"| Minimum in-scope top-1 similarity | {summary['min_in_scope']:.4f} |",
        f"| Maximum out-of-scope top-1 similarity | {summary['max_out_of_scope']:.4f} |",
        f"| Gap between the clusters | {summary['gap']:.4f} |",
        f"| **Chosen threshold T** | **{summary['threshold']:.4f}** |",
        "",
        "### Chunking comparison",
        "",
        "| Collection | Chunks | Mean \\|R\\| | Precision@3 | Recall@3 |",
        "|---|---|---|---|---|",
    ]
    for strategy in sorted(scores):
        name = config.COLLECTION_FOR_STRATEGY[strategy]
        _, precision, recall = scores[strategy]
        lines.append(
            f"| `{name}` | {counts[name]} | {mean_r[strategy]:.2f} | "
            f"{precision:.4f} | {recall:.4f} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    print("Part 1 - running every task under MOCK_LLM")
    print()

    print("Task 1: dataset")
    write("part1-dataset.txt", dataset_transcript())

    print("Task 3: chunking and indexing")
    index_body, counts = indexing_summary()

    print("Task 4: threshold calibration")
    summary = calibration.calibrate()
    write("part1-calibration.txt", index_body + "\n" + calibration.format_report(summary))

    print("Task 4: grounded generation")
    write("part1-generation.txt", generation_transcript())

    print("Task 5: chunking comparison")
    write("part1-evaluation.txt", evaluate.format_comparison())

    print("README number tables")
    write("part1-readme-numbers.md", readme_numbers(summary, counts))

    print()
    print(f"threshold in config.py: {config.SIMILARITY_THRESHOLD}")
    print(f"threshold measured now: {summary['threshold']}")
    if config.SIMILARITY_THRESHOLD != summary["threshold"]:
        print(
            "  NOTE: the measured midpoint has moved. Update config.SIMILARITY_THRESHOLD "
            "and README.md together, then re-run."
        )


if __name__ == "__main__":
    main()
