"""Run every Part 3 task in order and write the graded transcripts.

Nothing in README.md's Part 3 number block is typed by hand. This script
writes transcripts/part3-readme-numbers.md and README.md carries that block,
same rule as scripts/run_part1.py and scripts/run_part2.py, and the same
reason.
"""

import json
import os
import shutil
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
os.environ.setdefault("ANONYMIZED_TELEMETRY", "False")
# part3-logging.txt reads real http_request lines back from config.LOG_FILE.
# obs.py is quiet by default (D-70); this is the one runner that needs it
# turned up, and it has to happen before `import config` computes LOG_LEVEL.
# Not setdefault: `cp .env.example .env`, the command README.md gives, defines
# LOG_LEVEL with an empty value, and setdefault treats a present-but-empty key
# as already set. The runner then wrote no log lines and died on an IndexError
# three frames away from the cause. An explicit level the caller chose is still
# honoured; only an absent or empty one is filled in.
if not os.environ.get("LOG_LEVEL"):
    os.environ["LOG_LEVEL"] = "INFO"

import config  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

from agent import memory  # noqa: E402
from api.main import app  # noqa: E402
from eval import judge, triad  # noqa: E402
from rag import index  # noqa: E402

HEADER = (
    "Generated by scripts/run_part3.py under MOCK_LLM with zero API keys and\n"
    "zero network access. Reproduce with: .venv/bin/python scripts/run_part3.py\n"
)

client = TestClient(app)


def write(name: str, body: str) -> Path:
    config.TRANSCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    path = config.TRANSCRIPT_DIR / name
    path.write_text(f"{HEADER}\n{body}", encoding="utf-8")
    print(f"  wrote {path.relative_to(config.REPO_ROOT)}")
    return path


def fresh_ask(query: str, thread_id: str) -> dict:
    """One turn on a guaranteed-empty thread.

    Same reason as scripts/run_part2.py::fresh_ask: config.CONVERSATION_DIR
    persists one JSON file per thread across process runs, so without this
    the second run of this script resumes turn 2 and the trace_id, the turn
    number and the route can all move.
    """
    path = memory.path_for(thread_id)
    if path.exists():
        path.unlink()
    return client.post("/ask", json={"query": query, "thread_id": thread_id}).json()


def _show(payload) -> str:
    return json.dumps(payload, indent=2, sort_keys=True)


# --- Task 11, the API --------------------------------------------------------


def api_transcript() -> str:
    """Tasks 11 and 12's brief, section 22. One call to each endpoint, then
    the loop the /add-document endpoint exists to demonstrate: refuse an
    unsupported question, add the document that answers it, ask again.
    """
    lines = ["PART 3 TASK 11 - THE API", ""]

    lines.append("--- POST /ask, one call ---")
    ask_query = "How is the EMI on a loan calculated?"
    ask_response = fresh_ask(ask_query, thread_id="part3-api-ask")
    lines += [
        f"request : {_show({'query': ask_query})}",
        f"response: {_show(ask_response)}",
        "",
    ]

    lines.append("--- POST /add-document, one call ---")
    add_request = {
        "title": "Auto loan top-up eligibility",
        "body": (
            "An existing auto loan may be topped up after twelve paid EMIs "
            "with no missed instalment. The top-up amount cannot exceed the "
            "original sanctioned amount. A fresh eligibility check runs "
            "against the applicant's current credit score before approval."
        ),
        "products": ["Auto Loan"],
    }
    add_response = client.post("/add-document", json=add_request)
    lines += [
        f"request : {_show(add_request)}",
        f"response: {_show(add_response.json())} (status {add_response.status_code})",
        "",
    ]

    lines.append("--- THE REFUSE-ADD-ANSWER LOOP (D-72, D-53's union) ---")
    lines.append("")
    loop_query = "How long does a home loan take to disburse after approval?"
    lines.append(f"query: {loop_query!r}")
    lines.append("")
    lines.append("before any upload:")
    before = fresh_ask(loop_query, thread_id="part3-loop-before")
    lines += [_show(before), ""]

    loop_add_request = {
        "title": "Home loan disbursal timeline",
        "body": (
            "A sanctioned home loan is disbursed within seven working days of "
            "formal approval. Disbursement for a ready property is completed "
            "within seven working days of approval, released in one tranche. "
            "Disbursement for a property under construction is completed "
            "within seven working days of each approval milestone, released "
            "in stages. The seven working day disbursement clock starts on "
            "the date of formal loan approval."
        ),
        "products": ["Home Loan"],
    }
    lines.append("POST /add-document:")
    loop_add_response = client.post("/add-document", json=loop_add_request)
    lines += [
        f"request : {_show(loop_add_request)}",
        f"response: {_show(loop_add_response.json())}",
        "",
    ]

    lines.append("after the upload, the same query naming its catalogue product:")
    after = fresh_ask(loop_query, thread_id="part3-loop-after")
    lines += [_show(after), ""]

    lines += [
        "The query names Home Loan explicitly. Before D-53's product filter",
        "unioned in every doc id under data/uploads/, a query naming a",
        "catalogue product could never reach an upload - only the identical",
        "question with no product named could. Now it can, which is why this",
        "demo uses the product-naming form rather than the product-free one.",
        f"outcome moved from {before['policy']['outcome']!r} to "
        f"{after['policy']['outcome']!r}; top1_similarity moved from "
        f"{before['policy']['top1_similarity']} to "
        f"{after['policy']['top1_similarity']}.",
    ]
    return "\n".join(lines) + "\n"


# --- Task 12, the request log line --------------------------------------------


def _redact_duration(line: dict) -> dict:
    """Strip the one wall-clock number obs.py puts on every line (D-70).

    A transcript is a deliverable, not a log; two runs must be the same
    bytes, and duration_ms is real elapsed time, never reproducible to the
    millisecond. Everything else on the line - trace_id, path, status,
    query_masked - is deterministic and stays.
    """
    redacted = dict(line)
    if "duration_ms" in redacted:
        redacted["duration_ms"] = "<redacted, wall-clock, per D-70>"
    return redacted


def _log_line_count() -> int:
    if not config.LOG_FILE.exists():
        return 0
    return len([l for l in config.LOG_FILE.read_text(encoding="utf-8").splitlines() if l.strip()])


def _new_http_request_lines(before: int) -> list[dict]:
    text = config.LOG_FILE.read_text(encoding="utf-8") if config.LOG_FILE.exists() else ""
    lines = [json.loads(l) for l in text.splitlines()[before:] if l.strip()]
    return [l for l in lines if l.get("event") == "http_request"]


def _require_one(lines: list[dict], label: str) -> dict:
    """The first http_request line for `label`, or a readable failure.

    Reading zero lines back means obs.py was quiet, not that the request
    failed - the request above it succeeded either way. Indexing straight
    into the list reported that as an IndexError three frames from the
    cause, which is how an empty LOG_LEVEL in .env stayed invisible.
    """
    if not lines:
        raise SystemExit(
            f"No http_request log line was written for {label}. obs.py logs at "
            f"INFO and config.LOG_LEVEL is {config.LOG_LEVEL!r}; this runner needs "
            "INFO or DEBUG. Check LOG_LEVEL in the environment and in .env."
        )
    return lines[0]


def logging_transcript() -> str:
    """Task 12. Three requests, one carrying a fabricated PAN, read back
    from config.LOG_FILE rather than reasoned about - the same discipline
    test_api_logging.py applies through caplog, here applied to the real
    file a running deployment actually writes.
    """
    lines = ["PART 3 TASK 12 - THE REQUEST LOG LINE", ""]

    before = _log_line_count()
    fresh_ask("How is the EMI calculated?", thread_id="part3-log-plain")
    plain = _new_http_request_lines(before)

    before = _log_line_count()
    fresh_ask(
        "My PAN is FXZPG5049K, what is the minimum balance?",
        thread_id="part3-log-pan",
    )
    pan = _new_http_request_lines(before)

    before = _log_line_count()
    client.post("/add-document", json={
        "title": "Business loan collateral",
        "body": "A business loan above twenty lakh rupees requires collateral. " * 3,
        "products": ["Business Loan"],
    })
    add_document = _new_http_request_lines(before)

    lines += [
        "REQUEST 1 - a plain /ask, trace_id is the response's own (D-38, D-75)",
        _show(_redact_duration(_require_one(plain, "REQUEST 1"))),
        "",
        "REQUEST 2 - a fabricated PAN, masked before it is logged (D-71)",
        _show(_redact_duration(_require_one(pan, "REQUEST 2"))),
        "",
        "REQUEST 3 - /add-document, no AgentResponse, so trace_id is a hash",
        "of the canonical request body instead (D-38's rule, applied)",
        _show(_redact_duration(_require_one(add_document, "REQUEST 3"))),
    ]
    return "\n".join(lines) + "\n"


# --- Task 13, the RAG triad ---------------------------------------------------


def triad_transcript() -> tuple[str, dict]:
    """Task 13. Fifteen rows, three averages, and the row the triad exists for.

    IU-02 is answered, not refused - top1=0.4645 against T=0.3066, all three
    retrieved chunks parented under kb-12-nri-account-eligibility, so the
    >= 2 of 3 support rule passes too. Its groundedness reads inside the
    answerable band because the answer faithfully restates the wrong
    document; only context_relevance reads low, and that gap between one
    high signal and one low signal on the same row is the whole argument for
    scoring three things rather than one. It leads this transcript rather
    than waiting to be found in row 15 of 15.
    """
    from rag import generate

    rows = []
    for item in triad.triad_items():
        answered = generate.answer(item.text)
        scores = judge.score(
            item.text, answered.text, judge.context_of(answered.hits)
        )
        rows.append((item, answered, scores))

    by_id = {item.item_id: (item, answered, scores) for item, answered, scores in rows}
    iu02_item, iu02_answered, iu02_scores = by_id["IU-02"]

    ctx_avg = round(statistics.mean(s.context_relevance for _, _, s in rows), config.TRIAD_SCORE_PLACES)
    gnd_avg = round(statistics.mean(s.groundedness for _, _, s in rows), config.TRIAD_SCORE_PLACES)
    ans_avg = round(statistics.mean(s.answer_relevance for _, _, s in rows), config.TRIAD_SCORE_PLACES)

    lines = [
        "PART 3 TASK 13 - THE RAG TRIAD",
        "",
        "Under MOCK_LLM the three scores below are deterministic lexical",
        "proxies - n-gram containment between the query, the answer and the",
        "retrieved context - not a model's judgement (D-74). A real provider",
        "is asked the same three questions through the identical prompt.",
        "",
        "THE ROW THIS TABLE EXISTS TO SHOW",
        "",
        f"  {iu02_item.item_id} ({iu02_item.text!r}) is answered, not refused:",
        f"  top1={iu02_answered.top1_similarity} against T={config.SIMILARITY_THRESHOLD},",
        "  all three retrieved chunks parented under kb-12-nri-account-eligibility,",
        "  so the >= 2 of 3 support rule passes as well as the threshold.",
        f"  groundedness reads {iu02_scores.groundedness:.4f} - inside the answerable",
        "  band - because the answer faithfully restates the wrong document.",
        "  An answer that restates irrelevant context is grounded by",
        "  definition, so groundedness cannot catch this and was never the",
        f"  signal that could. context_relevance reads {iu02_scores.context_relevance:.4f}",
        "  instead, well below its own groundedness on the same row. That gap",
        "  - one high signal, one low signal, same answer - is the argument",
        "  for three signals rather than one; a triad that scored only",
        "  groundedness would call this row a success.",
        "",
        "EVERY ROW",
        f"  {'item_id':8} {'kind':18} {'context_rel':>11} {'grounded':>9} "
        f"{'answer_rel':>10}",
    ]
    for item, answered, scores in rows:
        marker = "  <-- see above" if item.item_id == iu02_item.item_id else ""
        lines.append(
            f"  {item.item_id:8} {item.kind:18} {scores.context_relevance:11.4f} "
            f"{scores.groundedness:9.4f} {scores.answer_relevance:10.4f}{marker}"
        )
    lines += [
        "",
        f"average context relevance: {ctx_avg:.4f}",
        f"average groundedness:      {gnd_avg:.4f}",
        f"average answer relevance:  {ans_avg:.4f}",
    ]
    numbers = {
        "context_relevance_avg": ctx_avg,
        "groundedness_avg": gnd_avg,
        "answer_relevance_avg": ans_avg,
        "row_count": len(rows),
    }
    return "\n".join(lines) + "\n", numbers


# --- The README number block -------------------------------------------------


def readme_numbers(triad_numbers: dict) -> str:
    """The block README.md carries. Never typed by hand."""
    return "\n".join(
        [
            "<!-- Generated by scripts/run_part3.py. Do not edit by hand. -->",
            "",
            "| Part 3 measurement | Value |",
            "|---|---|",
            f"| Triad rows scored | {triad_numbers['row_count']} |",
            f"| Average context relevance | {triad_numbers['context_relevance_avg']:.4f} |",
            f"| Average groundedness | {triad_numbers['groundedness_avg']:.4f} |",
            f"| Average answer relevance | {triad_numbers['answer_relevance_avg']:.4f} |",
            "",
            "<!-- End of generated block. -->",
            "",
        ]
    )


def require_mock_provider() -> None:
    """Refuse to write graded artefacts under a real provider (D-68).

    transcripts/ and the README number blocks are byte-guarded, and a real
    model is not bit-reproducible. Without this, one forgotten line in .env
    rewrites them and the diff looks like a legitimate retune.
    """
    provider = config.resolve_provider()
    if provider != config.DEFAULT_PROVIDER:
        sys.exit(
            f"Refusing to run: LLM_PROVIDER={provider!r}. This script writes "
            f"graded, byte-guarded artefacts and only {config.DEFAULT_PROVIDER!r} "
            f"is reproducible. Unset LLM_PROVIDER, or use "
            f"scripts/run_groq_demo.py to exercise the real provider."
        )


def require_no_stray_uploads() -> None:
    """Refuse to write graded artefacts while data/uploads/ holds a file.

    rag/retrieve.py's product narrowing reads config.UPLOAD_DIR live and
    unions its doc ids into every product-named query (D-72's V2 note). This
    is the one runner that legitimately writes uploads of its own - the API
    transcript's refuse-add-answer loop and the logging transcript's third
    request both call /add-document - so it also cleans up everything it
    created at the end of a successful run (see main()). This guard exists
    for the case that matters more: a file left by something else entirely -
    a manual /add-document session, a crashed test, an interrupted previous
    run of this same script - would silently join the union here too and
    move transcripts/ and the README number blocks, with no code change and
    no error. Refuse and say so, rather than silently deleting a file that
    might be someone's real work.
    """
    if config.UPLOAD_DIR.exists():
        stray = sorted(p.name for p in config.UPLOAD_DIR.iterdir())
        if stray:
            sys.exit(
                f"Refusing to run: {config.UPLOAD_DIR.relative_to(config.REPO_ROOT)} "
                f"holds {stray}. rag/retrieve.py's product narrowing reads this "
                f"directory live, so a stray upload would move graded, "
                f"byte-guarded artefacts with no code change. Clear it first: "
                f"rm -r {config.UPLOAD_DIR.relative_to(config.REPO_ROOT)}"
            )


def _clear_own_uploads() -> None:
    """Undo every /add-document call made so far, so what follows sees the
    same corpus scripts/run_part1.py and run_part2.py measure against (D-72's
    V2 rollback: a rebuild drops any collection whose count does not match
    the corpus on disk).

    Called twice: once between the API/logging transcripts and the triad
    one, so the triad's fifteen rows are scored against the plain corpus
    rather than against the corpus plus whatever the earlier demos uploaded -
    measured directly: EQ-01's groundedness read 0.7917 clean and 0.7200 with
    the API transcript's uploads still in the collection, because an
    unfiltered query's top-3 can include an unrelated upload. And once more
    at the very end, so the next run starts from the same corpus this one
    did. Both calls are safe only because require_no_stray_uploads already
    confirmed the directory started this run empty: by construction,
    whatever is in config.UPLOAD_DIR at either point is only what this run
    itself created, never a stray this script did not put there.
    """
    if config.UPLOAD_DIR.exists() and any(config.UPLOAD_DIR.iterdir()):
        index.build_index(rebuild=True)
        shutil.rmtree(config.UPLOAD_DIR)


def main() -> None:
    print("Part 3. Writing transcripts under MOCK_LLM.")
    require_mock_provider()  # before require_no_stray_uploads, both before any write
    require_no_stray_uploads()  # same reasoning as run_part1.py and run_part2.py

    write("part3-api.txt", api_transcript())
    write("part3-logging.txt", logging_transcript())

    _clear_own_uploads()  # the triad scores the plain corpus, not corpus + demo uploads

    triad_body, triad_numbers = triad_transcript()
    write("part3-triad.txt", triad_body)

    numbers_path = config.TRANSCRIPT_DIR / "part3-readme-numbers.md"
    numbers_path.write_text(readme_numbers(triad_numbers), encoding="utf-8")
    print(f"  wrote {numbers_path.relative_to(config.REPO_ROOT)}")

    _clear_own_uploads()
    print("Done.")


if __name__ == "__main__":
    main()
